# Generated by Django 4.1.2 on 2024-06-26 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('appaterno', models.CharField(max_length=20)),
                ('apmaterno', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('celular', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=500)),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='RayoMacween.genero')),
            ],
        ),
    ]
