# Generated by Django 4.1.2 on 2024-06-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RayoMacween', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='id',
            field=models.BigAutoField(auto_created=True, default=3, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulario',
            name='rut',
            field=models.CharField(max_length=10),
        ),
    ]
