# Generated by Django 4.1.2 on 2024-06-29 14:47

import RayoMacween.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RayoMacween', '0002_formulario_id_alter_formulario_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='id_genero',
            field=models.ForeignKey(db_column='idGenero', default=RayoMacween.models.Formulario.get_default_genero, on_delete=django.db.models.deletion.CASCADE, to='RayoMacween.genero'),
        ),
    ]
