# Generated by Django 4.1.2 on 2024-07-11 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RayoMacween', '0003_alter_formulario_id_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
