# Generated by Django 4.1.2 on 2024-07-03 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RayoMacween', '0002_categoria_cliente_producto_orden'),
        ('RayoMacween', '0003_alter_formulario_id_genero'),
    ]

    operations = [
    ]
