# Generated by Django 4.1.2 on 2024-07-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RayoMacween', '0004_formulario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10),
        ),
    ]
